# Generated by Django 5.1.3 on 2025-04-28 05:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Term name (e.g., 'Fall 2025')", max_length=50)),
                ('term', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], help_text='Term (Fall, Spring, Summer)', max_length=20)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=20)),
                ('start_date', models.DateField(help_text='Term start date')),
                ('end_date', models.DateField(help_text='Term end date')),
                ('registration_start', models.DateField(help_text='Registration start date')),
                ('registration_end', models.DateField(help_text='Registration end date')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this term is currently active')),
            ],
            options={
                'ordering': ['-academic_year', 'term'],
                'indexes': [models.Index(fields=['term', 'academic_year'], name='enrollment__term_8d9056_idx'), models.Index(fields=['is_active'], name='enrollment__is_acti_7f0ef5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='end_date_after_start_date'), models.CheckConstraint(condition=models.Q(('registration_end__gt', models.F('registration_start'))), name='registration_end_after_start')],
                'unique_together': {('term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('dropped', 'Dropped'), ('passed', 'Passed'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('waitlisted', 'Waitlisted')], default='registered', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True, help_text='Date of enrollment')),
                ('date_status_changed', models.DateTimeField(auto_now=True, help_text='Date of last status change')),
                ('grade', models.CharField(blank=True, help_text='Final grade if completed', max_length=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about enrollment', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-date_enrolled'],
                'indexes': [models.Index(fields=['section', 'status'], name='enrollment__section_29d702_idx'), models.Index(fields=['student', 'status'], name='enrollment__student_431ee3_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'section'), name='unique_student_section_enrollment'), models.CheckConstraint(condition=models.Q(('date_enrolled__lte', datetime.datetime(2025, 4, 28, 5, 44, 51, 406497, tzinfo=datetime.timezone.utc))), name='enrollment_date_not_future')],
            },
        ),
    ]
