# Generated by Django 5.1.3 on 2025-02-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Semester in which the student is enrolled (e.g., Fall, Spring)', max_length=50)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-2025)', max_length=20)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True, help_text='Date of enrollment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['academic_year', 'semester'],
                'unique_together': {('student', 'course', 'semester', 'academic_year')},
            },
        ),
    ]
