# Generated by Django 5.1.3 on 2025-04-28 06:41

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('enrollment', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_date_not_future',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('date_enrolled__lte', datetime.datetime(2025, 4, 28, 6, 41, 10, 813905, tzinfo=datetime.timezone.utc))), name='enrollment_date_not_future'),
        ),
    ]
