# Generated by Django 5.1.3 on 2025-02-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_rename_course_code_course_code_and_more'),
        ('enrollment', '0001_initial'),
        ('students', '0002_student_student_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_date_not_future',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('date_enrolled__lte', datetime.datetime(2025, 2, 28, 16, 12, 10, 185648, tzinfo=datetime.timezone.utc))), name='enrollment_date_not_future'),
        ),
    ]
