# Generated by Django 5.1.3 on 2025-04-28 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('enrollment', '0002_remove_enrollment_enrollment_date_not_future_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_date_not_future',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('date_enrolled__lte', datetime.datetime(2025, 4, 28, 7, 54, 20, 459832, tzinfo=datetime.timezone.utc))), name='enrollment_date_not_future'),
        ),
    ]
