# Generated by Django 5.1.3 on 2025-03-03 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_rename_course_code_course_code_and_more'),
        ('enrollment', '0005_remove_enrollment_enrollment_date_not_future_and_more'),
        ('students', '0004_remove_student_department_student_faculty'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_date_not_future',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('date_enrolled__lte', datetime.datetime(2025, 3, 3, 12, 22, 24, 399164, tzinfo=datetime.timezone.utc))), name='enrollment_date_not_future'),
        ),
    ]
