# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the classroom', max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students the classroom can hold')),
                ('building', models.CharField(blank=True, help_text='Building where the classroom is located', max_length=100, null=True)),
                ('has_projector', models.BooleanField(default=False, help_text='Does the classroom have a projector?')),
                ('has_whiteboard', models.BooleanField(default=True, help_text='Does the classroom have a whiteboard?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this classroom currently in use?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the classroom was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the classroom was last updated')),
                ('department', models.ForeignKey(blank=True, help_text='Department that owns the classroom', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('facility', models.ForeignKey(blank=True, help_text='Facility where the classroom is located', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
