# Generated by Django 5.1.3 on 2025-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Faculty name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Faculty code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Faculty description', null=True)),
                ('dean', models.CharField(blank=True, help_text='Name of the faculty dean', max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Office location of the faculty', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this faculty currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
    ]
