# Generated by Django 5.1.3 on 2025-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=100, unique=True)),
                ('faculty', models.CharField(blank=True, help_text='Faculty to which this department belongs', max_length=100, null=True)),
                ('head_of_department', models.CharField(blank=True, help_text='Name of the department head', max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, help_text='Office location of the department', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this department currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
