# Generated by Django 5.1.3 on 2025-03-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty to which this department belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='faculties.faculty'),
        ),
    ]
