/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcademicStaffStep: typeof import('./src/components/creation-flow/AcademicStaffStep.vue')['default']
    AcademicTermManagement: typeof import('./src/components/new/academic-management/AcademicTermManagement.vue')['default']
    AttendanceManagement: typeof import('./src/components/attendance/AttendanceManagement.vue')['default']
    AttendanceManagementView: typeof import('./src/components/NEW/AttendanceManagementView.vue')['default']
    BaseFormCard: typeof import('./src/components/common/BaseFormCard.vue')['default']
    BaseModal: typeof import('./src/components/modals/BaseModal.vue')['default']
    BaseStructureStep: typeof import('./src/components/creation-flow/BaseStructureStep.vue')['default']
    ClassroomManagementView: typeof import('./src/components/NEW/ClassroomManagementView.vue')['default']
    ClassroomSchedule: typeof import('./src/components/schedule/ClassroomSchedule.vue')['default']
    CollegeStructure: typeof import('./src/components/new/college-structure/CollegeStructure.vue')['default']
    CourseManagement: typeof import('./src/components/academic-management/CourseManagement.vue')['default']
    CourseManagementView: typeof import('./src/components/NEW/CourseManagementView.vue')['default']
    CourseStructureStep: typeof import('./src/components/creation-flow/CourseStructureStep.vue')['default']
    CreationCard: typeof import('./src/components/creation/CreationCard.vue')['default']
    DataTable: typeof import('./src/components/data-display/DataTable.vue')['default']
    EnrollmentManagement: typeof import('./src/components/new/academic-management/EnrollmentManagement.vue')['default']
    EntityForm: typeof import('./src/components/forms/EntityForm.vue')['default']
    ErrorHandler: typeof import('./src/components/common/ErrorHandler.vue')['default']
    ErrorNotification: typeof import('./src/components/common/ErrorNotification.vue')['default']
    FormActions: typeof import('./src/components/common/FormActions.vue')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    FormRow: typeof import('./src/components/common/FormRow.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListViewLayout: typeof import('./src/components/layouts/ListViewLayout.vue')['default']
    RFIDManagement: typeof import('./src/components/new/rfid-management/RFIDManagement.vue')['default']
    RFIDManagementView: typeof import('./src/components/NEW/RFIDManagementView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleFormDialog: typeof import('./src/components/schedule/ScheduleFormDialog.vue')['default']
    ScheduleManagement: typeof import('./src/components/new/scheduling/ScheduleManagement.vue')['default']
    ScheduleManagementView: typeof import('./src/components/NEW/ScheduleManagementView.vue')['default']
    SideBar: typeof import('./src/components/navigation/SideBar.vue')['default']
    StaffManagementView: typeof import('./src/components/NEW/StaffManagementView.vue')['default']
    StatusBadge: typeof import('./src/components/creation/StatusBadge.vue')['default']
    StudentEnrollmentStep: typeof import('./src/components/creation-flow/StudentEnrollmentStep.vue')['default']
    UserManagement: typeof import('./src/components/NEW/UserManagement.vue')['default']
    UserProfileView: typeof import('./src/components/NEW/UserProfileView.vue')['default']
  }
}
