/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcademicYearManager: typeof import('./src/components/academics/academic/AcademicYearManager.vue')['default']
    ActivityTypeManager: typeof import('./src/components/wallet/ActivityTypeManager.vue')['default']
    BaseForm: typeof import('./src/components/common/BaseForm.vue')['default']
    BaseLayout: typeof import('./src/components/layouts/BaseLayout.vue')['default']
    ClassroomManager: typeof import('./src/components/academics/academic/ClassroomManager.vue')['default']
    ContentCard: typeof import('./src/components/common/ContentCard.vue')['default']
    Filter: typeof import('./src/components/common/Filter.vue')['default']
    FormCard: typeof import('./src/components/common/FormCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    List: typeof import('./src/components/common/List.vue')['default']
    LoadingSkeleton: typeof import('./src/components/common/LoadingSkeleton.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MultiplierRulesManager: typeof import('./src/components/wallet/MultiplierRulesManager.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PageLayout: typeof import('./src/components/layouts/PageLayout.vue')['default']
    ProfileCard: typeof import('./src/components/users/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleTimetable: typeof import('./src/components/academics/ScheduleTimetable.vue')['default']
    SemesterManager: typeof import('./src/components/academics/academic/SemesterManager.vue')['default']
    SideBar: typeof import('./src/components/layouts/SideBar.vue')['default']
    StudentCard: typeof import('./src/components/users/StudentCard.vue')['default']
    StudentForm: typeof import('./src/components/users/StudentForm.vue')['default']
    TransactionManager: typeof import('./src/components/wallet/TransactionManager.vue')['default']
    WalletManager: typeof import('./src/components/wallet/WalletManager.vue')['default']
  }
}
