# Generated by Django 5.1.3 on 2025-02-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='Unique course code (e.g., CS101)', max_length=20, unique=True)),
                ('course_name', models.CharField(help_text='Course name (e.g., Introduction to Programming)', max_length=255)),
                ('credit_hours', models.PositiveIntegerField(default=3, help_text='Number of credit hours for the course')),
                ('semester_offered', models.CharField(blank=True, help_text='Semester when the course is offered (e.g., Fall, Spring)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the course', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this course currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Course creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Course last updated timestamp')),
                ('department', models.ForeignKey(help_text='Department offering this course', on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester this package applies to')),
                ('courses', models.ManyToManyField(related_name='included_in_packages', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='departments.department')),
            ],
            options={
                'ordering': ['semester'],
                'unique_together': {('department', 'semester')},
            },
        ),
    ]
