# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(help_text='Section identifier (e.g., A, B, 001)', max_length=10)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course__code', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='SectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section__course__code', 'section__section_number'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique course code (e.g., CS101)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Course name (e.g., Introduction to Programming)', max_length=255)),
                ('credits', models.PositiveIntegerField(default=3, help_text='Number of credit hours for the course')),
                ('semester', models.CharField(blank=True, help_text='Semester when the course is offered (e.g., Fall, Spring)', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the course', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this course currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Course creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Course last updated timestamp')),
                ('department', models.ForeignKey(help_text='Department offering this course', on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Prerequisite courses', to='courses.course')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester this package applies to')),
                ('courses', models.ManyToManyField(related_name='included_in_packages', to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_packages', to='departments.department')),
            ],
            options={
                'ordering': ['semester'],
            },
        ),
    ]
