# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
        ('enrollment', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='academic_term',
            field=models.ForeignKey(help_text='The academic term this section is offered in', on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='enrollment.academicterm'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='classrooms.classroom'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.coursesection'),
        ),
        migrations.AddField(
            model_name='sectionassignment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='schedules.timeslot'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'is_active'], name='courses_cou_departm_352b34_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_cou_code_612388_idx'),
        ),
        migrations.AddIndex(
            model_name='coursepackage',
            index=models.Index(fields=['department', 'semester'], name='courses_cou_departm_fa934f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursepackage',
            unique_together={('department', 'semester')},
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['academic_term', 'is_active'], name='courses_cou_academi_b1b932_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['course', 'academic_term'], name='courses_cou_course__0e5c2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'section_number', 'academic_term'), name='unique_course_section_in_term'),
        ),
        migrations.AddIndex(
            model_name='sectionassignment',
            index=models.Index(fields=['section'], name='courses_sec_section_0d4c24_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionassignment',
            index=models.Index(fields=['room', 'timeslot'], name='courses_sec_room_id_703d5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sectionassignment',
            constraint=models.UniqueConstraint(fields=('section', 'timeslot'), name='unique_section_timeslot'),
        ),
        migrations.AddConstraint(
            model_name='sectionassignment',
            constraint=models.UniqueConstraint(fields=('room', 'timeslot'), name='unique_room_timeslot'),
        ),
    ]
