"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-198jya$3n6^1l6lbp&__tiyepth7nu+$0tr_*@ay3_e7p^_@2y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []

AUTH_USER_MODEL = 'base.User'


# Application definition

INSTALLED_APPS = [
    # ---------- DEFAULT -----------

    # ------------------------------
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # -------- PLUG - INS --------
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django_filters',
    # ---------- LOCAL -----------
    # --- College ---
    'college.departments',
    'college.faculties',
    'college.courses',
    'college.classrooms',
    'college.facilities',  # NEW: Adds hostel, cafeteria, library, etc.
    'college.schedules',
    # ---
    # 'college.schedules.apps.SchedulesConfig',
    # 'college.courses.apps.CoursesConfig',
    # 'college.classrooms.apps.ClassroomsConfig',

    # --- Users ---
    'users.base',  # NEW: Common user authentication (login, roles)
    'users.staff',
    'users.lecturers',
    'users.students',

    # --- Attendance & Academic Records ---
    'academics.attendance',  # NEW: Tracks RFID-based attendance
    'academics.grades',  # NEW: Stores student grades & performance
    'academics.enrollment',  # NEW: Manages student course enrollment
    'academics.bindings',  # NEW: Many-to-many relationships between models

    # --- Transactions & Services ---
    'transactions.rfid',  # Renamed for clarity
    'transactions.payments',  # NEW: Handles cafeteria purchases, hostel payments

    # --- Security & Access Control ---
    'security.audit_logs',  # NEW: Tracks actions performed in the system
    'security.authentication',  # NEW: MFA, password resets, etc.

    # --- Utilities ---
    'utilities',  # Main utilities app
    'utilities.rfid_util',
    'utilities.notifications',  # NEW: SMS, email, push notifications
    'utilities.reports',  # NEW: Generates reports for admins

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # -------------------------------------
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------- CORS -----------------

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # Vue.js dev server
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # You can also configure pagination, authentication, etc.
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Student API',
    'DESCRIPTION': 'API for student management',
    'VERSION': '1.0.0',
    # 'ENUM_NAME_OVERRIDES': {
    #     'academics.attendance.ATTENDANCE_STATUS_CHOICES': 'AttendanceStatusEnum',
    #     'users.students.STUDENT_STATUS_CHOICES': 'StudentStatusEnum',
    # },
}

