# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['day_of_week'], name='schedules_t_day_of__ce95eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('day_of_week', 'start_time', 'end_time'), name='unique_timeslot')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional scheduling notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.coursesection')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.timeslot')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='schedules_s_is_acti_ae1f3d_idx'), models.Index(fields=['classroom', 'time_slot'], name='schedules_s_classro_be36b6_idx'), models.Index(fields=['section'], name='schedules_s_section_bef63c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('classroom', 'time_slot', 'section'), name='unique_active_classroom_timeslot_section'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('section', 'time_slot'), name='unique_active_section_timeslot')],
            },
        ),
    ]
