# Generated by Django 5.1.3 on 2025-02-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, help_text='Event name (for non-course events)', max_length=255, null=True)),
                ('instructor', models.CharField(blank=True, help_text='Instructor or speaker for the session', max_length=100, null=True)),
                ('start_time', models.DateTimeField(help_text='Start time of the session')),
                ('end_time', models.DateTimeField(help_text='End time of the session')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', help_text='Status of the session', max_length=20)),
                ('classroom', models.ForeignKey(blank=True, help_text='Classroom where the session will take place', null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroom')),
                ('course', models.ForeignKey(blank=True, help_text='Course associated with this schedule', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('facility', models.ForeignKey(blank=True, help_text='Facility used for the session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('classroom', 'start_time', 'end_time')},
            },
        ),
    ]
