# Generated by Django 5.1.3 on 2025-04-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('LECTURER', 'Lecturer Constraint'), ('ROOM', 'Room Constraint'), ('STUDENT', 'Student Constraint'), ('DEPARTMENT', 'Department Constraint')], max_length=20)),
                ('reference_id', models.IntegerField(help_text='ID of the entity this constraint applies to')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_unavailable', models.BooleanField(default=True, help_text='If True, entity cannot be scheduled during this time')),
                ('preference_weight', models.IntegerField(default=0, help_text='For preferred times: higher means stronger preference')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='schedules.timeslot')),
            ],
            options={
                'indexes': [models.Index(fields=['constraint_type', 'reference_id'], name='schedules_s_constra_4a486e_idx'), models.Index(fields=['day_of_week'], name='schedules_s_day_of__e165f7_idx')],
            },
        ),
    ]
