# Generated by Django 5.1.3 on 2025-02-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Unique RFID Tag ID', max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='Time when the RFID was issued')),
                ('last_written_at', models.DateTimeField(blank=True, help_text='Time when data was last written to the RFID tag', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
