# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Unique RFID Tag ID', max_length=50, unique=True)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for this card', unique=True)),
                ('card_status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned to Personnel'), ('WRITTEN', 'Written to Card'), ('ISSUED', 'Issued to User'), ('LOST', 'Lost/Stolen'), ('INACTIVE', 'Inactive')], default='PENDING', help_text='Current status of the physical RFID card', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('written_at', models.DateTimeField(blank=True, help_text='When the card was physically written', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this card')),
                ('assigned_to_personnel', models.ForeignKey(blank=True, help_text='Staff member responsible for writing this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rfid_cards', to='staff.staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFID Card',
                'verbose_name_plural': 'RFID Cards',
                'indexes': [models.Index(fields=['tag_id'], name='rfid_util_r_tag_id_203fba_idx'), models.Index(fields=['unique_identifier'], name='rfid_util_r_unique__59a567_idx'), models.Index(fields=['card_status'], name='rfid_util_r_card_st_d5eb16_idx')],
            },
        ),
    ]
