# Generated by Django 5.1.3 on 2025-02-25 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_util', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfidtag',
            name='last_written_at',
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfidtag',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rfidtag',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rfidtag',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rfidtag',
            index=models.Index(fields=['tag_id'], name='rfid_util_r_tag_id_2c7838_idx'),
        ),
    ]
