# Generated by Django 5.1.3 on 2025-02-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid_util', '0002_remove_rfidtag_last_written_at_rfidtag_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Unique RFID Tag ID', max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RFIDTag',
        ),
        migrations.AddIndex(
            model_name='rfidcard',
            index=models.Index(fields=['tag_id'], name='rfid_util_r_tag_id_203fba_idx'),
        ),
    ]
