# Generated by Django 5.1.3 on 2025-06-15 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned for this attendance')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive weekly attendance streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest weekly attendance streak achieved')),
                ('last_attendance_week', models.DateField(blank=True, help_text='Start date of the last week with attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_streak'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=9)),
                ('time_slot', models.PositiveSmallIntegerField(choices=[(1, '08:00 - 08:30'), (2, '08:30 - 09:00'), (3, '09:00 - 09:30'), (4, '09:30 - 10:00'), (5, '10:00 - 10:30'), (6, '10:30 - 11:00'), (7, '11:00 - 11:30'), (8, '11:30 - 12:00'), (9, '12:00 - 12:30'), (10, '12:30 - 13:00'), (11, '13:00 - 13:30'), (12, '13:30 - 14:00'), (13, '14:00 - 14:30'), (14, '14:30 - 15:00'), (15, '15:00 - 15:30'), (16, '15:30 - 16:00'), (17, '16:00 - 16:30'), (18, '16:30 - 17:00'), (19, '17:00 - 17:30'), (20, '17:30 - 18:00')])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField(help_text='Start date of the schedule')),
                ('end_date', models.DateField(help_text='End date of the schedule')),
                ('session_duration', models.PositiveSmallIntegerField(default=30, help_text='Duration of each session in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legacy Schedule',
                'verbose_name_plural': 'Legacy Schedules',
                'ordering': ['day', 'time_slot', 'classroom'],
            },
        ),
    ]
