# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this lecturer is the primary instructor')),
                ('role', models.CharField(blank=True, help_text="Specific role (e.g., 'Instructor', 'Lab Assistant', 'TA')", max_length=50, null=True)),
                ('hours_per_week', models.PositiveIntegerField(default=0, help_text='Estimated teaching hours per week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='lecturers.lecturer')),
            ],
            options={
                'ordering': ['-section__academic_term__start_date', 'section__course__code'],
            },
        ),
    ]
