# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bindings', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturercourse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_assignments', to='courses.coursesection'),
        ),
        migrations.AddIndex(
            model_name='lecturercourse',
            index=models.Index(fields=['lecturer'], name='bindings_le_lecture_b0c59b_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturercourse',
            index=models.Index(fields=['section'], name='bindings_le_section_201637_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturercourse',
            constraint=models.UniqueConstraint(fields=('lecturer', 'section', 'is_primary'), name='unique_lecturer_section_primary'),
        ),
    ]
