# Generated by Django 5.1.3 on 2025-04-28 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('GRADUATED', 'Graduated')], default='INACTIVE', help_text='Current student status', max_length=10)),
                ('semester', models.IntegerField(default=1)),
                ('student_number', models.CharField(blank=True, help_text='Unique student identifier in format S{YYYY}{0000}', max_length=10, null=True, unique=True)),
                ('rfid_tag', models.CharField(blank=True, help_text="Student's RFID card number", max_length=50, null=True, unique=True)),
                ('balance_points', models.PositiveIntegerField(default=0, help_text='Points for purchasing in college facilities')),
                ('enrolled_at', models.DateField(auto_now_add=True, help_text='Date of Registration')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculties.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
