# Generated by Django 5.1.3 on 2025-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, help_text='Unique student identifier in format S{YYYY}{0000}', max_length=10, null=True, unique=True),
        ),
    ]
