# Generated by Django 5.1.3 on 2025-03-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rfid_tag',
            field=models.CharField(blank=True, help_text="Student's RFID card number", max_length=50, null=True, unique=True),
        ),
    ]
