# Generated by Django 5.1.3 on 2025-02-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rfid_tag',
        ),
    ]
