# Generated by Django 5.1.3 on 2025-03-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_rfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Staff', 'Staff'), ('Admin', 'Admin')], help_text='User role in the system - assigned automatically based on profile type', max_length=20, null=True),
        ),
    ]
