# Generated by Django 5.1.3 on 2025-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Facility name', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Lab', 'Laboratory'), ('Lecture Hall', 'Lecture Hall'), ('Library', 'Library'), ('Cafeteria', 'Cafeteria'), ('Amphitheater', 'Amphitheater'), ('Hostel', 'Hostel'), ('Sports Center', 'Sports Center'), ('Other', 'Other')], help_text='Type of facility', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Location of the facility', max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity of the facility', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the facility currently in use?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
